# Generated by Django 2.1.12 on 2025-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('groupId', models.CharField(max_length=20, primary_key=True)),
                ('userId', models.CharField(max_length=20,)),
                ('projectTitle', models.CharField(max_length=100)),
                ('projectDesc', models.TextField()),
                ('image', models.ImageField(upload_to='productImages')),
                ('targetCount', models.IntegerField(default=0)),
                ('currentCount', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
    ]
