# Generated by Django 2.1.12 on 2025-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
