# Generated by Django 2.1.12 on 2025-08-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20250802_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='groupId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
