# Generated by Django 2.1.12 on 2025-08-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20250802_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userId',
            field=models.IntegerField(unique=True),
        ),
    ]
