# Generated by Django 2.1.12 on 2025-08-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20250803_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
