# Generated by Django 2.1.12 on 2025-08-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('address', models.BooleanField(default=False)),
                ('avatar', models.ImageField(upload_to='avatar')),
            ],
        ),
    ]
